fix e2e

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -51,6 +51,16 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: e2e tests
         run: |
+          if [ -f ".changelog/${{ github.event.pull_request.number }}.txt" ]; then
+              make changelogtest
+
+              if [ $? -ne 0 ]; then
+                  printf "COMMIT FAILED\n"s
+                  exit 1
+              fi
+              exit 0
+          fi
+
           make deltatest
           if [ $? -ne 0 ]; then
               printf "COMMIT FAILED\n"
